buildscript {
    repositories {
        jcenter()
        maven { url = "https://files.minecraftforge.net/maven" }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'

version = '1.0.11'
group = 'com.brilliafy.magicstorage'
archivesBaseName = 'MagicStorage'

sourceCompatibility = targetCompatibility = '1.8'
compileJava {
    sourceCompatibility = targetCompatibility = '1.8'
}

minecraft {
    version = "1.12.2-14.23.5.2847"
    runDir = "run"
    mappings = "stable_39"
    makeObfSourceJar = false
    replace '@VERSION@', project.version
    replaceIn "ModInfo.java"
}

getAssets.enabled = false

repositories {
    maven { url "https://dvs1.progwml6.com/files/maven" }
    maven { url "https://modmaven.dev/" }
    maven { url "https://maven.blamejared.com" }
    maven { url "https://www.cursemaven.com" }
    flatDir { dirs "/home/Aelfwif/Downloads/PrismLauncher-Linux-Qt6-Portable-11.0.3/instances/1.12.2/minecraft/mods" }
}

dependencies {
    deobfCompile "mezz.jei:jei_1.12.2:4.15.0.291"
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

jar {
    manifest {
        attributes([
            "Specification-Title": "MagicStorage",
            "Specification-Vendor": "brilliafy",
            "Specification-Version": "1",
            "Implementation-Title": project.name,
            "Implementation-Version": "${version}",
            "Implementation-Vendor": "brilliafy",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

jar.finalizedBy('reobfJar')
